### ISSUE TITLE
Build Difficulties

### ISSUE THREAD

**Issue by bretonio** [alexandesigner/quasar-meteor#1]
Following the build instructions &mdash; `npm run bundler` and `npm run api` &mdash; I discover that the `quasar dev` command as prescribed is not available. 

What **is** available is `npm run dev` which runs the demo app as expected. But I am unable to determine where to add my Quasar modules &mdash; in this case I want QToolbar and QToolbarTitle which it seems have not been loaded.  Would I maybe want to import these in `main.js`? 

Very educational project and I thank you.

**Comment by alexandesigner** [comment]
Thanks for the remark, I will correct .. but in case it did not run quasar start, because you did not have the quasar-cli installed globally, but your comment is valid.

The imports, in this example I imported into the Hello.vue file [Hello.vue](https://github.com/alexandesigner/quasar-meteor/blob/master/src/components/Hello.vue#L118) you will not need to import them into the [main.js](https://github.com/alexandesigner/quasar-meteor/blob/master/src/main.js#L19) because there I am already setting up the use of Quasar. [See](https://github.com/alexandesigner/quasar-meteor/blob/master/src/main.js#L19)

**Comment by alexandesigner** [comment]
@bretonio Let me know if you have any questions.
